### ISSUE TITLE
Simple self-referential YAML cannot be parsed.

### ISSUE THREAD

**Issue by clonezone** [PaulJuliusMartinez/jless#141]
Start with `self-referential.yaml`:

```yaml
--- &1
foo: bar
baz: *1
```

Try to look at that with v0.9.0:

```
> jless self-referential.yaml
Unable to parse input: "Unknown YAML parse error"
```
