### ISSUE TITLE
show comments in yaml files

### ISSUE THREAD

**Issue by theblop** [PaulJuliusMartinez/jless#164]
Is it possible to toggle comments in yaml files? It would be super useful for large commented yaml config files (e.g. helm chart value files)

Thanks!

**Comment by andres-lowrie** [comment]
Hey so this works with at least version `0.9.0`

> some file `foo.yaml`
```yaml
---

key:
  - value
  - value
  - value

key2:
  - object:
      key: value
      key: value
  - object:
      key: value
      key: value
  - object:
      key: value
      key: value

```

and then doing 

```
jless -m line foo.yaml
```

yields 

```json
{
  "key": [
    "value",
    "value",
    "value"
  ],
  "key2": [
    {
      "object": {
        "key": "value"
      }
    },
    {
      "object": {
        "key": "value"
      }
    },
    {
      "object": {
        "key": "value"
      }
    }
  ]
}
